In [1]:
import numpy as np

###Create a null vector of size 10 but the fifth value which is 1.

In [5]:
x=np.zeros(10)
x[4]=1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


###Create a vector with values ranging from 10 to 49.

In [7]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

###Create a 3x3 matrix with values ranging from 0 to 8

In [10]:
np.random.randint(0,9,(3,3))

array([[3, 0, 2],
       [5, 6, 4],
       [5, 4, 4]])

###Find indices of non-zero elements from [1,2,0,0,4,0]

In [12]:
y=np.nonzero([1,2,0,0,4,0])
print(y)

(array([0, 1, 4], dtype=int64),)


 ###Create a 10x10 array with random values and find the minimum and maximum values

In [15]:
x=np.random.rand(10,10)
x


array([[0.76074555, 0.13128525, 0.34990459, 0.13494108, 0.09257862,
        0.71410996, 0.48398317, 0.59318482, 0.05042232, 0.65085858],
       [0.80535576, 0.46195767, 0.57141481, 0.22437546, 0.4630478 ,
        0.7888496 , 0.48805307, 0.85366856, 0.00992332, 0.75807566],
       [0.20824946, 0.41888566, 0.68612505, 0.55222027, 0.08756233,
        0.13184258, 0.02755171, 0.55270133, 0.17119945, 0.45967344],
       [0.10171506, 0.56315041, 0.22808801, 0.27435831, 0.68071209,
        0.42449201, 0.64477857, 0.34214119, 0.24014843, 0.65984934],
       [0.69434082, 0.00724805, 0.99458406, 0.21381292, 0.32885358,
        0.08424297, 0.05665376, 0.14536372, 0.20688437, 0.13213161],
       [0.89912563, 0.63311518, 0.29965958, 0.41062702, 0.0599283 ,
        0.71462688, 0.41599943, 0.52968288, 0.23518522, 0.01786215],
       [0.25911877, 0.77838026, 0.49942   , 0.69567157, 0.49376383,
        0.40709163, 0.53585573, 0.18875975, 0.61224898, 0.7301402 ],
       [0.2401018 , 0.14151532, 0.6270746

In [16]:
x.min()

0.007248047039750571

In [17]:
x.max()

0.9945840591455996

###Create a random vector of size 30 and find the mean value

In [19]:
p=np.random.rand(30)
p

array([0.98574381, 0.9827937 , 0.95751733, 0.6585915 , 0.14264946,
       0.60307227, 0.06579507, 0.59556071, 0.37493218, 0.90743928,
       0.82732665, 0.76926265, 0.66914605, 0.21228254, 0.14378654,
       0.29854795, 0.29268388, 0.37996387, 0.82084693, 0.39095978,
       0.6253771 , 0.72334834, 0.52304508, 0.02214125, 0.76006695,
       0.22053786, 0.07723455, 0.19037223, 0.83381197, 0.72955142])

In [20]:
p.mean()

0.5261462963709932